[[CURRENCIES]]
code = "Poh"
issuer = "GD7E4PXMJHMPQCWVGIGDF7NWNURM5UGPFK6A3X3MCX6BWGTCIPE4ZLHK"
display_decimals = 6
desc = "Poh(President One Hour)는 제21대 대통령 이재명님의 국정철학과 국민의 시간을 상징하는 특별한 스텔라 기반 토큰입니다."
image = "https://yesoklab.github.io/assets/poh.png"
