# YesOkLab Issuer Information
[ISSUER]
name = "YesOkLab"
website = "https://www.ljmsider.com" # YesOkLab 공식 홈페이지 주소
contact = "YesOkLab@gmail.com"
description = "블록체인 기술을 통해 사회적으로 가치 있는 기록과 유산을 디지털 자산으로 영구히 보존하는 디지털 레거시 프로젝트 The LJM Clockwork의 발행사입니다."

# LOH Token Information
[[CURRENCY]]
currency = "LOH"
issuer = "r95GJxcghgMyQXittPHjYZvGUMWfVwtzPs" # LOH 토큰의 발행자 XRP Ledger 주소
name = "LOH Token"
description = "LOH는 '대한민국 제21대 이(L)재명 대통령의 (1hour) 1시간은 대한민국 국민의 수 51,169,148명과 같다는 상징적인 의미를 담고 있습니다."
website = "https://www.ljmsider.com/project-ljm" # LJM Clockwork 프로젝트 페이지 주소 (예시, 실제 페이지 경로에 따라 변경 필요)
image = "ipfs://bafybeidociwexvnbzntakduzfld7rywb4rwshx6ch36d2b4qb2mvbw5zlq/loh_coin_transparent_512x512.png" # LOH 토큰 이미지 IPFS 주소
# 또는 IPFS 게이트웨이 주소 사용 (더 넓은 호환성)
# image = "https://ipfs.io/ipfs/bafybeidociwexvnbzntakduzfld7rywb4rwshx6ch36d2b4qb2mvbw5zlq/loh_coin_transparent_512x512.png"
# social_links = [
#     { type = "twitter", url = "https://x.com/YesOkLab" },
#     { type = "telegram", url = "https://t.me/YesOkLab_NFT" }
# ]
