[[CURRENCIES]]
currency = "PLJMOH"
issuer = "0x2Cb13fB3743315691b90Aa0B960d08BcF64F56F3"
name = "President Lee Jae-myung of Hope"
desc = "PLJMOH is a symbolic meme token representing the will of Korean citizens to support transparency and democracy through blockchain. Created in support of Lee Jae-myung."
url = "https://yesoklab.github.io"
image = "https://yesoklab.github.io/.well-known/pljmoh.png"

[[CURRENCIES]]
currency = "PLJMOH"
issuer = "0x2Cb13fB3743315691b90Aa0B960d08BcF64F56F3"
name = "이재명대통령의1시간(PLJMOH) -이재명 대통령의 한시간은 대한민국 국민 모두의 51,169,148 시간 입니다."
desc = "PLJMOH는 국민의 투명한 정치 참여를 토큰입니다. 이재명 대통령의 1시간은 위대한 대한민국 국민인구 수 51,169,148 시간으로 블록체인화 하였습니다."
url = "https://yesoklab.github.io"
image = "https://yesoklab.github.io/.well-known/pljmoh.png"

